export const NZ_TOWNS = [
  'Ahipara', 'Akaroa', 'Albany', 'Albert Town', 'Albury', 'Alexandra', 'Allanton',
  'Amberley', 'Anakiwa', 'Arrowtown', 'Arundel', 'Ashburton', 'Ashhurst', 'Ashley',
  'Auckland', 'Awanui', 'Balclutha', 'Balfour', 'Bannockburn', 'Beachlands', 'Beaumont',
  'Bell Block', 'Benhar', 'Benneydale', 'Blackball', 'Blenheim', 'Bluff', 'Brighton',
  'Brightwater', 'Broadwood', 'Bulls', 'Burnham', 'Cambridge', 'Canvastown', 'Carterton',
  'Cheviot', 'Christchurch', 'Clarksville', 'Clive', 'Clyde', 'Coalgate', 'Collingwood',
  'Coromandel', 'Cromwell', 'Culverden', 'Cust', 'Dannevirke', 'Darfield', 'Dargaville',
  'Devonport', 'Doyleston', 'Drury', 'Dunedin', 'Duntroon', 'Eastbourne', 'Edgecumbe',
  'Egmont Village', 'Eketahuna', 'Eltham', 'Fairfax', 'Fairlie', 'Featherston', 'Feilding',
  'Fielding', 'Flaxmere', 'Fox Glacier', 'Foxton', 'Foxton Beach', 'Frankton', 'Franz Josef',
  'Geraldine', 'Gisborne', 'Glenorchy', 'Glentunnel', 'Gore', 'Granity', 'Greymouth',
  'Greytown', 'Grovetown', 'Haast', 'Havelock', 'Havelock North', 'Hawarden', 'Hawera',
  'Helensville', 'Henley', 'Herekino', 'Hikurangi', 'Hinds', 'Hokitika', 'Hope', 'Howick',
  'Hunterville', 'Huntly', 'Inglewood', 'Invercargill', 'Jacobs River', 'Kaiapoi',
  'Kaikohe', 'Kaikoura', 'Kaitaia', 'Kaitangata', 'Kaiwharawhara', 'Kakanui', 'Kakaramea',
  'Kaponga', 'Karamea', 'Karetu', 'Katikati', 'Kawakawa', 'Kawerau', 'Kennedy Bay',
  'Kerikeri', 'Kimbolton', 'Kingston', 'Kinloch', 'Kohukohu', 'Kokatahi', 'Kurow',
  'Lake Hawea', 'Lake Tekapo', 'Lawrence', 'Leeston', 'Leigh', 'Lepperton', 'Levin',
  'Lincoln', 'Linkwater', 'Little River', 'Lower Hutt', 'Lumsden', 'Lyell', 'Lytton',
  'Makarewa', 'Manaia', 'Manakau', 'Manapouri', 'Mangakino', 'Mangamuka', 'Mangaweka',
  'Mapua', 'Maraetai', 'Martinborough', 'Marton', 'Masterton', 'Matamata', 'Matata',
  'Maungaturoto', 'Mayfield', 'Methven', 'Middlemarch', 'Midhurst', 'Millers Flat',
  'Milton', 'Moana', 'Moenui', 'Moeraki', 'Moerewa', 'Mokau', 'Morrinsville', 'Mosgiel',
  'Motueka', 'Mount Cook', 'Mount Maunganui', 'Murchison', 'Murupara', 'Napier', 'Naseby',
  'Nelson', 'New Brighton', 'New Plymouth', 'Ngatea', 'Ngaruawahia', 'Normanby', 'Norsewood',
  'Oakura', 'Oamaru', 'Oban', 'Ohakune', 'Ohaupo', 'Ohaeawai', 'Ohoka', 'Ohura', 'Okaihau',
  'Okato', 'Omanaia', 'Omarama', 'Omokoroa', 'Opononi', 'Opotiki', 'Opua', 'Opunake',
  'Orari', 'Orewa', 'Otautau', 'Otaki', 'Otane', 'Otorohanga', 'Owaka', 'Oxford',
  'Paekakariki', 'Pahiatua', 'Paihia', 'Palmerston', 'Palmerston North', 'Papakura',
  'Paraparaumu', 'Patea', 'Pauanui', 'Pegasus', 'Pencarrow', 'Petone', 'Picton',
  'Piopio', 'Pipiriki', 'Pleasant Point', 'Plimmerton', 'Porirua', 'Portland',
  'Pukekohe', 'Putaruru', 'Queenstown', 'Raetihi', 'Raglan', 'Rai Valley', 'Rangiora',
  'Ranfurly', 'Rapahoe', 'Rakaia', 'Rawene', 'Reefton', 'Renwick', 'Richmond',
  'Riverton', 'Rolleston', 'Ross', 'Rotorua', 'Roxburgh', 'Ruatoria', 'Ruawai',
  'Runanga', 'Russell', 'Saint Arnaud', 'Saint Bathans', 'Saint Kilda', 'Sanson',
  'Seacliff', 'Seddon', 'Seddonville', 'Sheffield', 'Silverdale', 'Snells Beach',
  'Spring Creek', 'Springfield', 'Springs Junction', 'St Andrews', 'Stirling',
  'Stratford', 'Sumner', 'Taihape', 'Taipa-Mangonui', 'Tairua', 'Takaka', 'Tapanui',
  'Tapawera', 'Taradale', 'Taupo', 'Taumarunui', 'Tauranga', 'Te Anau', 'Te Aroha',
  'Te Awamutu', 'Te Karaka', 'Te Kauwhata', 'Te Kuiti', 'Te Puke', 'Temuka', 'Thames',
  'The Wood', 'Timaru', 'Tirau', 'Tokaanu', 'Tokoroa', 'Tolaga Bay', 'Turangi',
  'Twizel', 'Tuatapere', 'Upper Hutt', 'Urenui', 'Waiheke Island', 'Waihi', 'Waihi Beach',
  'Waikanae', 'Waikouaiti', 'Waimate', 'Wainuiomata', 'Waipawa', 'Waipu', 'Waipukurau',
  'Wairakei', 'Wairoa', 'Waitahuna', 'Waitara', 'Waitati', 'Waitoa', 'Waitomo Caves',
  'Waitotara', 'Waiuku', 'Wakefield', 'Wallacetown', 'Warkworth', 'Waverley', 'Wellington',
  'Wellsford', 'Westport', 'Whakatane', 'Whangamata', 'Whanganui', 'Whangarei',
  'Whataroa', 'Whenuapai', 'Whitianga', 'Winton', 'Woodend', 'Woodville', 'Wyndham'
];
