import type { Question, Questions, Option } from '@/types';
import {
  Home,
  Car,
  Building2,
  ShieldQuestion,
  KeyRound,
  ShieldCheck,
  ShieldOff,
  MapPin,
  FileText,
  HeartHandshake,
  CircleDollarSign,
  User,
  Calendar,
  Contact,
  Landmark,
  Blocks,
  Phone,
  Mail,
  MessageSquare,
  Building,
  Wrench,
  Laptop,
  Hotel,
  BedDouble,
  Building as BuildingIcon,
  ChevronsUp,
  CarFront,
  Bike,
  Truck,
  Gem,
  CalendarClock,
  Heart,
  Activity,
  FileDigit,
  Users,
  Cigarette,
} from 'lucide-react';

export const TOTAL_STEPS_ESTIMATE = 8;

export const ALL_QUESTIONS: Questions = {
  'start': {
    id: 'start',
    question: "Welcome to QuoteFlow",
    Icon: Home,
    nextStepId: 'insurance-type',
  },
  'insurance-type': {
    id: 'insurance-type',
    question: "What type of insurance do you need?",
    description: "Select the main type of cover you're looking for.",
    Icon: ShieldQuestion,
    options: [
      { value: 'life', label: 'Life Insurance', icon: Heart, nextStepId: 'security-systems' },
      { value: 'trauma', label: 'Trauma Insurance', icon: Activity, nextStepId: 'security-systems' },
      { value: 'income', label: 'Income Protection', icon: FileDigit, nextStepId: 'security-systems' },
      { value: 'mortgage', label: 'Mortgage Protection', icon: Home, nextStepId: 'security-systems' },
    ],
  },
  'home-property-type': {
    id: 'home-property-type',
    question: 'What type of property is it?',
    Icon: Home,
    nextStepId: 'security-systems',
    options: [
      { value: 'house', label: 'House', icon: Home },
      { value: 'apartment', label: 'Apartment', icon: Building },
      { value: 'townhouse', label: 'Townhouse', icon: Hotel },
      { value: 'unit', label: 'Unit/Flat', icon: BedDouble },
    ],
  },
  'vehicle-type': {
    id: 'vehicle-type',
    question: 'What type of vehicle do you want to insure?',
    Icon: Car,
    nextStepId: 'vehicle-year',
     options: [
      { value: 'car', label: 'Car', icon: CarFront },
      { value: 'motorcycle', label: 'Motorcycle', icon: Bike },
      { value: 'truck', label: 'Truck/Ute', icon: Truck },
      { value: 'other', label: 'Other', icon: ShieldQuestion },
    ],
  },
   'vehicle-year': {
    id: 'vehicle-year',
    question: 'How old is the vehicle?',
    Icon: Calendar,
    nextStepId: 'security-systems',
     options: [
      { value: 'newer-3', label: '0-3 years old' },
      { value: '3-10', label: '3-10 years old' },
      { value: 'older-10', label: '10+ years old' },
    ],
  },
  'business-type': {
    id: 'business-type',
    question: 'What is your business type?',
    Icon: Building2,
    nextStepId: 'security-systems',
    options: [
        { value: 'trades', label: 'Trades & Services', icon: Wrench },
        { value: 'professional', label: 'Professional Services', icon: Laptop },
        { value: 'retail', label: 'Retail', icon: BuildingIcon },
        { value: 'other', label: 'Other' }
    ]
  },
  'landlord-property-type': {
    id: 'landlord-property-type',
    question: 'What type of property do you rent out?',
    Icon: KeyRound,
    nextStepId: 'security-systems',
    options: [
      { value: 'house', label: 'House', icon: Home },
      { value: 'apartment', label: 'Apartment', icon: Building },
      { value: 'multi-unit', label: 'Multi-unit Dwelling', icon: ChevronsUp },
    ],
  },
  'security-systems': {
    id: 'security-systems',
    question: 'Who do you want to cover?',
    Icon: Users,
    nextStepId: 'previous-claims',
    options: [
      { value: 'myself', label: 'Myself', icon: User },
      { value: 'myself-and-partner', label: 'Myself & partner', icon: Users },
    ],
  },
  'previous-claims': {
    id: 'previous-claims',
    question: 'Do you have an existing policy?',
    Icon: FileText,
    nextStepId: 'coverage-level',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
    ],
  },
  'coverage-level': {
    id: 'coverage-level',
    question: 'Have you smoked in the past 12 months?',
    Icon: Cigarette,
    nextStepId: 'age',
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No' },
    ],
  },
  'coverage-recommendation': {
    id: 'coverage-recommendation',
    question: 'Getting your recommendation...',
    Icon: ShieldQuestion,
    nextStepId: 'age'
  },
  'age': {
    id: 'age',
    question: 'How old are you?',
    Icon: User,
    fields: ['age'],
    nextStepId: 'coverage-start-date',
  },
  'age-group': {
    id: 'age-group',
    question: "What's your age group?",
    Icon: User,
    nextStepId: 'coverage-start-date',
    options: [
      { value: '18-25', label: '18 - 25' },
      { value: '26-40', label: '26 - 40' },
      { value: '41-60', label: '41 - 60' },
      { value: '60+', label: '60+' },
    ],
  },
  'coverage-start-date': {
    id: 'coverage-start-date',
    question: 'When do you need coverage to start?',
    Icon: CalendarClock,
    nextStepId: 'contact-details',
    options: [
      { value: 'immediately', label: 'Immediately' },
      { value: 'within-1-month', label: 'Within 1 month' },
      { value: '1-3-months', label: '1 - 3 months' },
      { value: 'researching', label: 'Just researching' },
    ],
  },
  'location': {
    id: 'location',
    question: 'What is your location?',
    description: 'Please provide your postcode so we can find local deals.',
    Icon: MapPin,
    fields: ['postcode'],
    nextStepId: 'contact-details',
  },
  'contact-details': {
    id: 'contact-details',
    question: 'How can we send your quote?',
    description: "Please provide your contact information to receive your personalized quote.",
    Icon: Contact,
    fields: ['name', 'email', 'phone'],
    nextStepId: 'results'
  },
  'results': {
    id: 'results',
    question: 'Your Quote Results',
    Icon: Gem,
  },
};
