import type { Question, Questions, Option } from '@/types';
import {
  Home,
  MapPin,
  Zap,
  Sun,
  Battery,
  Calculator,
  DollarSign,
  Calendar,
  Contact,
  Mail,
  Phone,
  User,
  Building,
  Building2,
  Wrench,
  TrendingUp,
  Lightbulb,
  Gauge,
  FileText,
  CheckCircle,
  BarChart3,
  Leaf,
  Shield,
} from 'lucide-react';

export const TOTAL_STEPS_ESTIMATE = 8;

export const SOLAR_QUESTIONS: Questions = {
  'start': {
    id: 'start',
    question: "Welcome to Your Solar Journey",
    description: "Let's calculate your solar savings and find the perfect system for your home.",
    Icon: Sun,
    nextStepId: 'property-type',
  },
  'property-type': {
    id: 'property-type',
    question: 'What type of property do you own?',
    description: "This helps us understand your roof structure and installation requirements.",
    Icon: Home,
    nextStepId: 'roof-type',
    options: [
      { value: 'house', label: 'Single Family House', icon: Home },
      { value: 'apartment', label: 'Apartment/Unit', icon: Building },
      { value: 'townhouse', label: 'Townhouse', icon: Building2 },
      { value: 'commercial', label: 'Commercial Building', icon: Building },
    ],
  },
  'roof-type': {
    id: 'roof-type',
    question: 'What type of roof do you have?',
    description: "Different roof types affect installation complexity and cost.",
    Icon: Home,
    nextStepId: 'roof-condition',
    options: [
      { value: 'tile', label: 'Tile Roof', icon: Home },
      { value: 'metal', label: 'Metal/Colorbond', icon: Shield },
      { value: 'concrete', label: 'Concrete Slab', icon: Building },
      { value: 'asbestos', label: 'Asbestos (needs replacement)', icon: Wrench },
      { value: 'other', label: 'Other/Not Sure', icon: FileText },
    ],
  },
  'roof-condition': {
    id: 'roof-condition',
    question: 'What is the condition of your roof?',
    description: "We need a structurally sound roof for safe solar installation.",
    Icon: CheckCircle,
    nextStepId: 'current-bill',
    options: [
      { value: 'excellent', label: 'Excellent (less than 5 years old)', icon: CheckCircle },
      { value: 'good', label: 'Good condition', icon: TrendingUp },
      { value: 'fair', label: 'Fair (some wear but stable)', icon: Gauge },
      { value: 'poor', label: 'Poor (needs repair/replacement)', icon: Wrench },
    ],
  },
  'current-bill': {
    id: 'current-bill',
    question: 'What is your average quarterly electricity bill?',
    description: "This helps us size your system to maximize savings.",
    Icon: DollarSign,
    nextStepId: 'energy-usage',
    options: [
      { value: 'under-300', label: 'Under €300', icon: DollarSign },
      { value: '300-500', label: '€300 - €500', icon: DollarSign },
      { value: '500-800', label: '€500 - €800', icon: DollarSign },
      { value: '800-1200', label: '€800 - €1,200', icon: DollarSign },
      { value: 'over-1200', label: 'Over €1,200', icon: TrendingUp },
    ],
  },
  'energy-usage': {
    id: 'energy-usage',
    question: 'When do you use most of your electricity?',
    description: "This affects battery storage recommendations and system design.",
    Icon: Lightbulb,
    nextStepId: 'battery-interest',
    options: [
      { value: 'day', label: 'Mostly during the day', icon: Sun },
      { value: 'evening', label: 'Evenings and weekends', icon: Lightbulb },
      { value: 'night', label: 'Night time (shift work)', icon: Calendar },
      { value: 'all-day', label: 'Throughout the day', icon: BarChart3 },
    ],
  },
  'battery-interest': {
    id: 'battery-interest',
    question: 'Are you interested in battery storage?',
    description: "Batteries store excess solar energy for use when the sun isn't shining.",
    Icon: Battery,
    nextStepId: 'timeline',
    options: [
      { value: 'yes', label: 'Yes, include battery storage', icon: Battery },
      { value: 'maybe', label: 'Maybe, show me options', icon: Calculator },
      { value: 'no', label: 'No, just solar panels', icon: Sun },
      { value: 'future', label: 'Not now, but battery-ready system', icon: Zap },
    ],
  },
  'timeline': {
    id: 'timeline',
    question: 'When would you like to install solar?',
    description: "This helps us prioritize your quote and installation scheduling.",
    Icon: Calendar,
    nextStepId: 'contact-info',
    options: [
      { value: 'asap', label: 'As soon as possible', icon: CheckCircle },
      { value: '1-3months', label: 'Within 1-3 months', icon: Calendar },
      { value: '3-6months', label: 'Within 3-6 months', icon: Calendar },
      { value: 'exploring', label: 'Just exploring options', icon: FileText },
    ],
  },
  'contact-info': {
    id: 'contact-info',
    question: 'Let\'s get your personalized solar quote',
    description: "We'll send you a detailed quote with savings calculations and system recommendations.",
    Icon: Contact,
    nextStepId: 'results',
    fields: [
      {
        name: 'firstName',
        label: 'First Name',
        type: 'text',
        required: true,
        icon: User,
      },
      {
        name: 'lastName',
        label: 'Last Name', 
        type: 'text',
        required: true,
        icon: User,
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        icon: Mail,
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'tel',
        required: true,
        icon: Phone,
      },
      {
        name: 'address',
        label: 'Property Address',
        type: 'text',
        required: true,
        icon: MapPin,
        placeholder: 'Street address for installation',
      },
    ],
  },
  'results': {
    id: 'results',
    question: 'Your Solar Assessment Results',
    description: "Based on your answers, here's your personalized solar solution.",
    Icon: Calculator,
    nextStepId: null,
  },
};

export const ALL_QUESTIONS: Questions = SOLAR_QUESTIONS;